### ISSUE TITLE
yay, postgres!

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#102]
postgres on RDS goes up to 9.3.5 currently, which is fantastic. let's just get off the sad leaky mysql boat before we have any data to migrate. :neckbeard:

**Comment by nchapman** [comment]
:+1:

**Comment by pdehaan** [comment]
![](https://31.media.tumblr.com/d74f0feb7c0d5c20bda9c9632cbb15cc/tumblr_inline_nhbnj4wNRV1raprkq.gif)

**Comment by 6a68** [comment]
that is the weirdest gif I've seen in a while. /me tips cap

**Comment by 6a68** [comment]
done except for the create test data bit, multi inserts are slightly curious in node-postgres

**Comment by 6a68** [comment]
should have this ready for testing early tomorrow :beers:
