### ISSUE TITLE
Use Lout for route docs?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#108]
Not sure if this is useful or not (but may be handy if running in development/local dev mode). I don't know that I'm comfortable with this going into Prod as an endpoint (not sure why, it's easy to see the endpoints in source anyways), but yeah, we can probably put a handy switch and only include Lout if your `config.get('env')` is "local", "awsdev", or "test" in [`NODE_ENV`](https://github.com/mozilla/chronicle/blob/9767c8d0d595d98cf06e4ecb884951d543328b83/server/config.js#L13-L18) -- or just add a Boolean config flag for "showApiDocs".

Just for giggles, I did an `npm i lout -D` and then added the [Lout](https://github.com/hapijs/lout) plugin to our `server.register()` call (where `Lout` was `var Lout = require('lout');`'ed earlier):

```js
server.register([
  HapiAuthCookie,
  Bell,
  Lout
], function (err) {
```

Now when I goes to http://localhost:8080/docs I see the following sauce:
![documentation_for_rest_routes](https://cloud.githubusercontent.com/assets/557895/5714774/49ae2116-9a82-11e4-8b0a-41087c0bb3b9.png)
**Figure 1:** Route list

![documentation_for](https://cloud.githubusercontent.com/assets/557895/5714797/770ec944-9a82-11e4-8ade-9771c24fb6f2.png)
**Figure 2:** Route details

**Comment by pdehaan** [comment]
Here's an earlier example I did for Hapi 7.x; https://github.com/pdehaan/hapi-examples/blob/master/hapi-lout/server.js

We can exclude certain routes from Lout docs and may force us to add some basic docs to the route configs, but Lout does a pretty good job of adding the expected parameters and required parameters and other basic docs automatically.

**Comment by pdehaan** [comment]
Actually, this works pretty well... It looks like we just need to add a `description`, `notes`, and `tags` attribute in the `config` object for each route (see screenshot below). I can't see any way to add descriptions for specific parameters yet though. Sadly, the docs aren't very good, and even looking through the source and templates isn't much help. I don't think it's possible.

```js
{
  method: 'DELETE',
  path: '/v1/visits/{visitId}',
  config: {
    description: 'THis is a description...',
    notes: 'This is a note',
    tags: ['visits'],

    auth: 'session',
    validate: {...},
    handler: function (request, reply) {...}
  }
}
```

![documentation_for](https://cloud.githubusercontent.com/assets/557895/5731074/79a21096-9b34-11e4-87df-5653724a46ce.png)

**Comment by 6a68** [comment]
@pdehaan maybe the description could contain information on the parameters? It seems weird that Joi-based validation isn't included in the docs

**Comment by pdehaan** [comment]
@6a68 There seems to be at least _some_ sense of Joi awareness... For example, in the screenshot above, it knows that `visitId` is a string and a Guid. But I can't find any way to set a description for that `visitId` parameter which is what I assume most people would want. I guess I could file a bug w/ Lout and see what they say.

If you want to me to add Lout into the mix, feel free to assign it to me and I can take a stab at it. Or if you don't think it's worth it, you can close it out with a whimsical GIF.

**Comment by 6a68** [comment]
Ultimately it's up to @nchapman. I kinda feel I owe him something better than autogenerated docs, which is why I'm putting some handwritten stuff in API.md. But, good intentions != keeping those docs up to date. ¯\_(ツ)_/¯

**Comment by pdehaan** [comment]
![](http://www.reactiongifs.us/wp-content/uploads/2014/05/why_not_both.gif)
