### ISSUE TITLE
psql: FATAL:  role "postgres" does not exist

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#118]
Success!
Postgres seems to be repaired (9.4.0 via Homebrew on OS X 10.10.1), and now gives me the following error(s) when trying to run `./server/db/create_db.sh`:

```sh
$ ./create_db.sh
psql: FATAL:  role "postgres" does not exist
psql: FATAL:  role "postgres" does not exist
psql: FATAL:  role "postgres" does not exist
psql: FATAL:  role "postgres" does not exist
psql: FATAL:  role "postgres" does not exist
psql: FATAL:  role "postgres" does not exist
psql: FATAL:  role "postgres" does not exist
psql: FATAL:  role "chronicle" does not exist
psql: FATAL:  role "chronicle" does not exist
psql: FATAL:  role "chronicle" does not exist
```

**Comment by pdehaan** [comment]
I'm not sure that this is the same set of errors that @dannycoates was seeing in https://github.com/mozilla/chronicle/pull/113#issuecomment-70168763

**Comment by dannycoates** [comment]
yep, i got that

**Comment by nchapman** [comment]
Yeah I'm getting the same. What's the right fix here? Travis needs the postgres role defined like we have here. Should we make this a param we pass into the script and have it default to `$USER`?

**Comment by 6a68** [comment]
@nchapman great idea

**Comment by 6a68** [comment]
I think this has been fixed for a while
