### ISSUE TITLE
I want Chronicle to be turned off while I'm in private mode

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#151]

**Comment by johngruen** [comment]
Seems like this will be the default behavior for the initial chronicle add-on. By way of explanation see [1] the mockup for the chroncile FTE-loading experience and the [2] current working build of the same.

[1] https://www.dropbox.com/s/fyehf3xpt6f5hki/Chronicle%20First%20Use.mov?dl=0
[2] https://people.mozilla.org/~jgruen/chronicle/#loading

**Comment by nchapman** [comment]
Since this is the default behavior, I'm going to close this one for now.
