### ISSUE TITLE
Add ver.json route to dev/stage/prod servers

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#214]
Not sure where this is generally injected, but we'll need this set up so we know what'd deployed in each environment.

ie: https://chronicle.dev.mozaws.net/ver.json

Here's what we do for [fxa-content-server](https://latest.dev.lcip.org/ver.json):
```js
{
  version: "0.29.0",
  commit: "71aca8403cbfc717572303f793f131180a317617",
  l10n: "bb53fd5e8f",
  tosPp: "29ec46747a"
}
```

Where `version` is from the package.json file, and `commit` is the currently deployed Git SHA.
The `l10n` and `tosPp` are Git SHAs to the respective bower repos.

**Comment by 6a68** [comment]
@pdehaan you're assigned, do you think you'll have time this week? if not, assign to me and I'll get at it

**Comment by 6a68** [comment]
there's always the copypasta option...maybe this could be an npm module eventually? https://github.com/mozilla/fxa-content-server/blob/master/server/lib/routes/get-ver.json.js

**Comment by pdehaan** [comment]
You had me at copy/paste.
See #325
