### ISSUE TITLE
Home page isn't updating after sign in/sign out

### ISSUE THREAD

**Issue by nchapman** [mozilla/chronicle#219]
The home page seems to often be the wrong version of the page when a user first signs in or signs out. It requires a force reload to get the proper version of the page.

**Comment by 6a68** [comment]
This seems like one of those Backbone.history things, I bet it's a trivial fix...maybe just `window.location.reload(true)` when the cookie is set or unset?

**Comment by nchapman** [comment]
I think it's actually on the server side (or maybe browser caching). You get `index.html` on the redirect after signing in and you get `app.html` on the redirect when signing out.

**Comment by nchapman** [comment]
I looked into this more last night and it seems the server is sending back a 304 when the browser checks to see if the page has changed. I tried to mess with cache control headers in hapi but became sad and gave up. Definitely appears to be a hapi issue though.

**Comment by nchapman** [comment]
http://hapijs.com/tutorials/caching#cache-control

**Comment by 6a68** [comment]
nchapman: looool @ "became sad and gave up". You just described my first 2 weeks with hapi.

I'm guessing the base route is the only one we'll need to update...but IIRC grunt-hapi sets up some super infuriating hidden route deep under node_modules, which might have caching stuff configured to the default levels.

We can try something like this for the base route, I'm just sketching here, this is definitely wrong, but you get the idea:
```
{
  method: 'GET',
  path: '/public/{path*}',
  config: {
    cache: {
      privacy: 'private', // tell intermediate caches not to store the page
      expiresIn: 100 // I'm kinda afraid setting it to 0 will trigger some goofy "0 means never expires" logic
    },
    handler: {
      directory: {
        path: '/path/to/public/stuff'
      }
    }
  }
}
```

**Comment by 6a68** [comment]
expiresIn is milliseconds till expiration, so I think it should just always refetch the page. @pdehaan interested in taking this one?

**Comment by pdehaan** [comment]
Weird. This is working in Chrome but not the first time in Firefox (although my caching prefs may be slightly different).

Odder is that I can reproduce it via `$ ./bin/www` as well, so I can't even blame **grunt-hapi**.

**Comment by pdehaan** [comment]
Setting to `expiresIn: 0` or `expiresIn: 1` doesn't seem to help.
But it only seems to happen once and then work, so I have to restart my local server to see the quirky behavior.
