### ISSUE TITLE
create service for sending transactional emails (sendmail locally, SES in the cloud)

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#22]
- when a user registers, send them a welcome email
    - user settings should include an email preference (later)

**Comment by billmaggs** [comment]
Legal questions and answers  related to use of email service will be posted here: https://etherpad.mozilla.org/ChronicleLegal

**Comment by 6a68** [comment]
@pdehaan Any interest in taking this on next week?

My thoughts for an initial pass:

- We do a "new vs existing user" check inside the [bell-oauth-profile](https://github.com/mozilla/chronicle/blob/master/server/bell_oauth_profile.js#L40-L49) file, and call `user.create` if the fxa id isn't found. It seems like the `user.create` function is the natural place to kick off a job to send an introductory email to new users. (I think it's fine to just source the work queue from inside the model; I very awkwardly tried to enforce a singleton queue pattern by attaching the queue to the hapi server, and exposing it via `server.methods`, seems complicated and unnecessary now (shouldn't require caching make it effectively a singleton anyway?). Soon, I'd like to have a global event broker object we can use to decouple the queue from the code that sends jobs to the queue, but we don't need to deal with that just yet.)
- Create a job that fires an introductory email: one liner, plain text, no html, no l10n, that welcomes {{ email }} to chronicle. for now, it's fine to just put all this code (including the one-liner "template", sendmail code, etc) inside the job; eventually, we'll pick a nice abstraction to keep the code in the job minimal.
- Register this new job with the work queue
- I think node-resque detects and automatically re-queues jobs that throw an error, so I think your job code should throw if it fails / times out
- it would be great to have this working locally with sendmail, and in aws with SES. seems to make sense to have these as strategies, and pick your strategy based on the environment. could be as simple as two files that export `function send(email, name, cb)`, or something. (I wonder if hapi has off-the-shelf sendmail code?)

Sound interesting? If not, I'm happy to find other stuff if you've got time to hack, let me know.
