### ISSUE TITLE
flatten config.js for ops sanity + remove env vars

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#220]

**Comment by 6a68** [comment]
I kinda like the nested config file for local dev, maybe this shameful ops requirement could be shuffled into a grunt task

**Comment by nchapman** [comment]
Yeah I like the nesting too...

**Comment by pdehaan** [comment]
![](http://media.tumblr.com/252b76874a672501e540cc4f079f63c3/tumblr_inline_nirsd9LDtw1r79k32.gif)

**Comment by 6a68** [comment]
OK, @nchapman and I talked this over. For the sake of just getting stuff done, I'll just flatten it and replace dots with underscores, so that `config.get('server.foo-bar')` becomes `config.get('server_foo-bar'`
