### ISSUE TITLE
fixup db creation 

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#221]
database creation code is a super hack and we need to do something better, by end of sprint

- constraints:
  - would be nice to just be a simple node script, since it runs so early
  - maybe not too much gruntiness
  - see #116?

**Comment by pdehaan** [comment]
Also see #120 for another option. There was also a [**grunt-pg**](https://github.com/moneytribeaustralia/grunt-pg) module by some @chilts guy, but that hasn't been updated in a couple years.

**Comment by chilts** [comment]
That `grunt-pg` really is a terrible way of doing it. I made and released that during an old contract and was asked to do it. I don't recommend it I'm afraid. :)

There is also `pg-patcher` I made a while ago. I quite like this approach : https://www.npmjs.com/package/pg-patcher

Note: the mysql-patcher we use in the fxa-auth-db-server is based on the above pg-patcher : https://www.npmjs.com/package/mysql-patcher

Both of these allow for sequential patch levels which can sometimes get annoying. I've been thinking lots about having patches depend on other ones in a not-necessarily sequential manner. I made this as a helper for such a module, but nothing has come about so far : https://www.npmjs.com/package/dep-tree

Anyway, some options there - ping me some more if I can be of help.

**Comment by chilts** [comment]
And see this as an example helper script, much like you're suggesting @6a68. Generally used in dev/testing (in package.json) but not used in production:

* https://github.com/mozilla/fxa-auth-db-server/blob/master/bin/db_patcher.js

**Comment by 6a68** [comment]
thanks for the feedback, @chilts!

I'm pretty happy that test data creation uses the [real code path](https://github.com/mozilla/chronicle/blob/master/bin/create_test_data.js#L54), now that #224 has landed...maybe we just punt on this until we figure out "to ORM or not to ORM" (issue #92 and maybe others?). Moving to the next sprint.

**Comment by 6a68** [comment]
main missing things: insert password and insert hostname

**Comment by 6a68** [comment]
I'm going to look through some `node-postgres` projects on github and see how people are handling this. Also will look at whether knex/sequelize handle postgres database creation cleanly.

One appealing option is just to have ops do the database and user creation steps at the command-line with the postgres `createdb` and `createuser` tools. Creating a database, in particular, can't be done as part of a transaction, and multi-line SQL is transactional by default.

If we assume the database and user exist, it becomes really simple to have a node script that uses the existing postgres helper to create the tables and indexes.

**Comment by 6a68** [comment]
In fact, now that I think about it, if we're on RDS, we probably will already have the user and database and hostname info, and won't need our script to create them.

**Comment by 6a68** [comment]
talked this over with @nchapman: let's split out the create_db vs create_schema tasks. That way ops can skip the create_db step in favor of something smarter.
1. use `createdb` and `createuser` to make sure these already exist
2. then just move the schema creation code back into `node-postgres`

**Comment by pdehaan** [comment]
Move everything to ElasticSearch and dump the db?

**Comment by 6a68** [comment]
this is fixed up enough for one sprint: we've moved all the table creation into a `pg-patcher` migration, good enough for now, I think. @nchapman shout if I'm forgetting something critical
