### ISSUE TITLE
Default favicon images should be transparent

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#237]
https://github.com/mozilla/chronicle/blob/master/app/images/icon-favicon_default%402x.png (and the non-retina version) aren't transparent, which can cause some mild hilarity for `.small` results which currently have a gray background.

![chronicle](https://cloud.githubusercontent.com/assets/557895/5986324/acb1b9e2-a8a8-11e4-9e76-e3349baca915.png)
**Figure 1:** Non-transparent default favicon.

![new_issue_ _mozilla_chronicle](https://cloud.githubusercontent.com/assets/557895/5986325/cb3975da-a8a8-11e4-8ba4-725e842207b7.png)
**Figure 2:** Absurd zoom.

**Comment by nchapman** [comment]
Fixed in #241.
