### ISSUE TITLE
I want to see more than one page of my visits

### ISSUE THREAD

**Issue by nchapman** [mozilla/chronicle#243]
We should like page or endless scroll or something on the front-end...

**Comment by 6a68** [comment]
Currently, fetching the "next older" page of items off the tail of the list should just require sending down the oldest seen visitId + optionally the count of items you want back: `GET /v1/visits?visitId=:id`

Related: do we want to add an "insert newer visits" button at the top of the feed?

Fetching the "next newer" page of items isn't implemented; you could just fetch the 25 newest, or we could add something to fetch, say, the 10 newest, 10 newer than the newest visitId already shown, and a button to reveal missing stuff in between...but now this is starting to sound super fancy ;-)

**Comment by 6a68** [comment]
@nchapman and I talked about this, we'll just do a "click t osee more" on desktop for now, with the existing visits api, and plan to add infinite scroll soon for mobile

**Comment by 6a68** [comment]
fixed by #267
