### ISSUE TITLE
I want to install the Firefox add-on

### ISSUE THREAD

**Issue by nchapman** [mozilla/chronicle#247]
This sounds easy, but we have to figure out how to build/host/update [the add-on](https://github.com/mozilla/chronicle-addon).

**Comment by 6a68** [comment]
The simplest option might be to publish to AMO under some kind of stealthy codename

**Comment by nchapman** [comment]
This is what Blake is doing on [Whimsy](https://github.com/bwinton/whimsy):

> It’s pretty simple, all in all.  I’ve got [a build target](https://github.com/bwinton/whimsy/blob/master/Gruntfile.js#L9) that has the options you need to pass to “cfx xpi”, and then [another one](https://github.com/bwinton/whimsy/blob/master/Gruntfile.js#L39) that copies the files to the server.  (I use ExpanDrive, so it’s just a file copy, but I’ve also used [rsync](https://github.com/bwinton/device-sharing-spec/blob/master/Gruntfile.js#L167).)
