### ISSUE TITLE
I want to stay signed into Chronicle between browser restarts

### ISSUE THREAD

**Issue by nchapman** [mozilla/chronicle#248]
Right now each time a user restarts their browser they have to sign in. This causes trouble for the add-on since it's using the same authentication.

**Comment by 6a68** [comment]
@nchapman and I chatted about this in IRC. let's change the cookie to be set to one year isntead of session cookie

**Comment by nchapman** [comment]
@6a68 should we make any changes to the defaults in the code or just set this per environment?

**Comment by 6a68** [comment]
@nchapman Hey, so the cookie duration is determined by the `server_session_duration` config, which is currently one day in the [sample local config](https://github.com/mozilla/chronicle/blob/master/config/local.json.example#L33), but we currently [default](https://github.com/mozilla/chronicle/blob/master/server/config.js#L268-L271) to a session cookie.

On my machine, it looks like the local session does persist after a browser restart. (BTW, just for context, the cookie is set [here](https://github.com/mozilla/chronicle/blob/master/server/index.js#L52).)

I'll just change the default to a year's worth of milliseconds, and we can call this done :-)

**Comment by nchapman** [comment]
There's another option to extend the cookie after each request. We could do
that and set the cookie for a month and it would keep extending as long as
your browser was sending history. Better or worse than fixed year?

**Comment by 6a68** [comment]
¯\_(ツ)_/¯

I guess it's better, in the sense that people who tend to use it more will want to extend their sessions, while people who never use it won't. So i'll update the PR

**Comment by 6a68** [comment]
I tried to use waffle.io on mobile...I guess this got reopened when I was trying to zoom in.
