### ISSUE TITLE
Scraper should discard embedly results with type:error

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#257]
Not sure what flow is happening here. I'm visiting http://pto.mozilla.org/ (needs LDAP password, but I'm logged in), but Chronicle displays the title as "401 Authorization Required".

Scraping the page with Embedly (web) gives me a rather unpleasant red bar:
http://embed.ly/docs/explore/extract?url=http%3A%2F%2Fpto.mozilla.org%2F

> _The URL you entered is not supported by embedly. If you think it should be, tell us here._

But what I'm not understanding is why, if the page title is being returned by the Firefox add-on, and the actual page title (in Firefox) is "Mozilla PTO", where is the title being set as "401 Authorization Required".

It definitely LOOKS like that 401 is coming from Embed.ly. Here's the [neutered] output from my embedly CLI tool:

```json
{
  "cache_age": 80525,
  "content": null,
  "description": null,
  "error_code": 401,
  "error_message": "HTTP 401: Unauthorized",
  "lead": null,
  "original_url": "http://pto.mozilla.org",
  "provider_display": "intranet.mozilla.org",
  "provider_name": "Mozilla",
  "provider_url": "https://intranet.mozilla.org",
  "published": null,
  "safe": true,
  "title": null,
  "type": "error",
  "url": "https://intranet.mozilla.org/pto/"
}
```

**Comment by 6a68** [comment]
Nice catch, @pdehaan! Once we get the happy paths sketched out more completely, it'll be great to add some logic to the scraper to handle common error cases like this.

**Comment by 6a68** [comment]
not clear if type:error is returned when embedly itself times out, or if it's just a 401

**Comment by pdehaan** [comment]
Yeah, it would probably be useful to log all the errors and just not display them on the front end so we can audit the errors and see if we can find trends.
Here's a snippet from my localhost w/ sample data and an "error" `extractedType`:

```js
{
  _index: "chronicle",
  _type: "userPages",
  _id: "98f605d0-dd25-4bf8-bf57-124921564fb5",
  _score: 1,
  _source: {
    extractedCacheAge: 79608,
    extractedContent: null,
    extractedDescription: null,
    extractedFaviconUrl: null,
    extractedLanguage: null,
    extractedLead: null,
    extractedProviderDisplay: "sfbay.craigslist.org",
    extractedProviderName: "Craigslist",
    extractedProviderUrl: "http://sfbay.craigslist.org",
    extractedSafe: true,
    extractedTitle: null,
    extractedType: "error",
    extractedUrl: "http://sfbay.craigslist.org/search/apa",
    extractedAt: "2015-02-17T01:03:25.719Z",
    userId: "a6c9411418f94710a712ab97e7a3541c",
    url: "http://sfbay.craigslist.org/search/apa",
    title: "SF bay area apts/housing for rent - craigslist",
    urlHash: "7bbcb539b960fd6f349b1fcaec9dc431c3ecbb35"
  }
},
```
