### ISSUE TITLE
enable users to view their chronicle history

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#26]
- need user account system
- need to accept visit input
- generate a view (most recent first?) of the history via API, so front-end can visualize it

**Comment by 6a68** [comment]
fixed by #72, closing.

@nchapman I guess we can just do separate server and front-end issues for big features, since they'll be closed by different PRs. Sound good?

**Comment by nchapman** [comment]
Yep that works for me. In the future, let's put something API related in the server issues title like: Create API to view chronicle history.
