### ISSUE TITLE
Need to proxy favicon images to avoid HTTP+HTTPS fraternization

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#261]
Per https://github.com/mozilla/chronicle/issues/259#issuecomment-72745916 wherein @nchapman says:

>> _something similar for the favicons since some of those are HTTP and others are HTTPS_

> _Yeah we do need to fix that... either through the display endpoint or the crop endpoint. Will you create an issue for this if we don't have one?_

Here's what I currently see in mein Firefox console when loading https://chronicle.dev.mozaws.net/:

![chronicle](https://cloud.githubusercontent.com/assets/557895/6030810/0208f654-abaf-11e4-8f51-4369c1138cec.png)
**Figure 1:** "Loading mixed (insecure) display content on a secure page "http://emberjs.com/images/favicon.png" [Learn More]"

**Comment by pdehaan** [comment]
And here's the devtools spew from Google Chrome:

![chronicle_and_chronicle](https://cloud.githubusercontent.com/assets/557895/6030887/a0fd62ea-abaf-11e4-8bdc-42d2a4c672ac.png)

**Comment by nchapman** [comment]
[Fixed](https://github.com/mozilla/chronicle/pull/272#discussion_r24107785) in #272.
