### ISSUE TITLE
Display general category for visit

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#263]
In the [Chronicle mockups](https://mozilla.invisionapp.com/share/8K23PH75H#/screens/59752942) we list things like **(Tech)**, **(Video)**, etc.

![0002_search](https://cloud.githubusercontent.com/assets/557895/6032180/02f0dfd0-abbb-11e4-9344-45a6e5de954a.png)
**Figure 1:** "Tech" category.

I'm not sure how we map URLs or keywords to categories, but we can probably ~~steal~~ "borrow" the logic from [Interest Dashboard](https://github.com/mozilla/interest-dashboard).

There is a lot of crazy data in [**mozilla/interest-dashboard**/refData](https://github.com/mozilla/interest-dashboard/tree/master/refData) that I don't know how we could share (unless it's a crude `npm install firefox-interest-dashboard` and cross our fingers). Maybe we just build some API endpoint where we pass in a URL and it returns a crude category &mdash; although I'd expect a lot more URL misses than hits, so we'd maybe need a second API which tries to map keywords from embedly and map those to random categories. I tried digging through the ID code, but ...

**Comment by pdehaan** [comment]
We may be able to cheat for now and just display one of "Article", "Audio", "Image", or "Video" based on the [media type](http://embed.ly/docs/api/extract/endpoints/1/extract#media) or [response `type`](http://embed.ly/docs/api/extract/response#extract-response-types) (where "Article" is the default if we didn't parse the destination as an audio, image, or video file.

**Comment by nchapman** [comment]
@pdehaan great find on the interest dashboard data. We've all been talking about tracking that down so thanks for doing that! We can leave out the categories for now, but I do think they'll be key to making our data easier to explore.

**Comment by pdehaan** [comment]
Hey, I just found the repo, interpreting that JSON seems non-trivial (at least to this QA brain).
They're using some space age use of `let` and `yield` and cool ES6-isms like `const {Cc, Ci, Cu} = require("chrome");` and even some `=>` fat arrow stuff.

But maybe we can hack some of this code out: https://github.com/mozilla/interest-dashboard/blob/master/test/test-UrlClassifier.js

I'm still not sure if that is a Node.js package or just some Node code in a repository. I guess the simple test would be to see if I can `npm install` it and see what happens.

**Comment by 6a68** [comment]
Dude. Amazing find, @pdehaan! One of my open todos was to figure out what the interest dashboard code looked like.

Pretty sweet that they have a ton of the url-to-interest-keyword special case mappings done already (https://github.com/mozilla/interest-dashboard/tree/master/data/models/en-US/rules).

Their repo's README says you use the addon sdk to build it, but it seems like we could convert it to a node service pretty easily. I'm going to close + refile this as a backlogged bug for creating an interest mining / categorization service using their data.
