### ISSUE TITLE
Decide on a standard way to define breakpoint-based styles

### ISSUE THREAD

**Issue by johngruen** [mozilla/chronicle#271]
Let's define how we we treat big/small only styles in our partials

**Comment by johngruen** [comment]
@pdehaan 
http://i.giphy.com/S4CTButEaN4vm.gif

**Comment by nchapman** [comment]
This might be overkill but it reads nicely: http://breakpoint-sass.com/

**Comment by johngruen** [comment]
@nchapman any tech blog post that's really about Point Break is alright by me.

**Comment by nchapman** [comment]
lol so true. What else is there to talk about...?

**Comment by nchapman** [comment]
Fixed in #293.
