### ISSUE TITLE
Visit create failure

### ISSUE THREAD

**Issue by nchapman** [mozilla/chronicle#276]
Seeing this error on dev:

```
chronicle.server.models.visit.WARN: models.visit.create elasticsearch insert failed
chronicle.server.work-queue.jobs.create-visit.WARN: failed at visit.create step for visit url https://github.com/mozilla/chronicle :Error: DocumentAlreadyExistsException[[chronicle][2] [userPages][d5b93eec-7db1-43a4-8147-ba118e38a507]: document already exists]
chronicle.server.work-queue.WARN: worker failed, job will be retried in 10 seconds
```

**Comment by 6a68** [comment]
wat

**Comment by 6a68** [comment]
the work queue sometimes doesn't properly detect that a job succeeded. given that the error is that the UUID is already in elasticsearch, and you didn't get that error from postgres, that's my guess

**Comment by 6a68** [comment]
Hmm, we're running short on time this sprint, so while it's not my first choice, I'm going to close this in favor of the work queue hardening bug #210, and defer looking at this till later.
