### ISSUE TITLE
User info box in the header doesn't seem to work locally or on dev server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#279]
Per @nchapman's https://github.com/mozilla/chronicle/pull/266#issue-56478373, I'm not seeing this anymore when testing against master locally, or on the https://chronicle.dev.mozaws.net/ dev server.

**Comment by nchapman** [comment]
I think it's `display: none` at the moment. Hopefully it'll be back soon (#278).

**Comment by johngruen** [comment]
@nchapman @pdehaan: yeah i think this is fixed by #286
