### ISSUE TITLE
Delete visit has a REALLLLLLLY generous hit target.

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#280]
Probably a temporary issue, but I'm a firm believer in "see something, file something".

It seems that the entire `<li>` works as a click target, and extends horizontally across the entire footer area.

![chronicle](https://cloud.githubusercontent.com/assets/557895/6050213/a91e02ea-ac72-11e4-806b-92f1a6789886.png)

It also seems I can fix it by changing the destroy HTML to `<a href="#" class="destroy">Destroy</a>` so now only the text triggers the super awesome `confirm()` item delete UX. I think I traced it back to a recent change, so not sure why we made this fix:
https://github.com/mozilla/chronicle/pull/272/files#diff-589ed4b6805c6296d743549e3301977eR11

**Comment by nchapman** [comment]
This shouldn't issue for long. I moved the class up to the `li` because we hide that on search results. Once this is styled, I think the click target will be appropriately sized.

**Comment by nchapman** [comment]
More thoughts: we can move the click event down to the anchor, but I figured we might end up changing which elements we use here anyway.

**Comment by johngruen** [comment]
Fixed by #292

**Comment by nchapman** [comment]
This appears to still be an issue in Firefox and Chrome.

**Comment by nchapman** [comment]
Fixed in #306.
