### ISSUE TITLE
Search not finding pages by keywords in description

### ISSUE THREAD

**Issue by nchapman** [mozilla/chronicle#324]
#### Search for msngr.js

![screen shot 2015-02-11 at 9 24 11 am](https://cloud.githubusercontent.com/assets/3095/6152153/c3ef02a6-b1cf-11e4-91a8-eb3b8063eef4.png)

#### Search for 'small messaging library' from description

![screen shot 2015-02-11 at 9 25 58 am](https://cloud.githubusercontent.com/assets/3095/6152184/0430f4fa-b1d0-11e4-927a-22cceb4fad2e.png)

**Comment by 6a68** [comment]
easy fix, just add the field here: https://github.com/mozilla/chronicle/blob/master/server/models/visits.js#L84
