### ISSUE TITLE
Replace node-resque with kue

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#363]
Just need something maintained that works, and kue does have much better docs.

**Comment by 6a68** [comment]
need an 'fml' or 'node.js smh' tag for these kinds of "unplanned refactoring" bugs...

**Comment by evantahler** [comment]
Hi! I'm that guy who made `node-resque`.  I was googling around for comparisons between `node-resque` and `kue`, and found this.  Why did you make the switch?  What wasn't working out for you?

Thanks!
