### ISSUE TITLE
'grunt server' should set process timezone to UTC

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#61]
We want timestamps on the server to always be in UTC.

This won't be a problem in real servers, but when developing locally, there are a couple ways this can fail:

1. The MySQL server needs to have its timezone set to UTC. Otherwise it'll store the TIMESTAMP fields as UTC, but convert them to the local timezone in query results.
  - This can be easily fixed by sending the query `SET time_zone=+00:00`. I'm adding this to the logic that grabs a connection from the connection pool.
2. Node needs to have its timezone set to UTC, via `process.env.TZ`, **before** starting the server.
  - Trying to set this on a running process produces non-deterministic results; see [this bug](https://github.com/joyent/node/issues/3286) for details.
  -  When node-mysql gets a timestamp from the database, it converts it into a Date object, which is formatted to the system local time.
  - Other workarounds for node-mysql returning results in PST aren't attractive:
    - use the deprecated node-mysql `typeCast` function to write a custom type mapping for dates (ughhh) ([example](https://github.com/felixge/node-mysql/issues/635#issuecomment-28314096))
    - manually handle this in the db layer and hope we don't miss a spot

The simplest workaround is to ensure that the env var 'TZ' has been set before the server starts. I'm not sure how to map this request to grunt's declarative syntax. @pdehaan any thoughts on how best to handle this?

**Comment by pdehaan** [comment]
Re: bullet 2, not sure if we can cheat and just specify the `process.env.TZ` arg via the CLI (using something like `npm start`, where `npm start` runs `$ TZ=+00:00 grunt serve`)... But not sure how well that'd play with the `grunt watch` server restarts.

**Comment by 6a68** [comment]
@pdehaan in that case, should we see if grunt can call something like forever or nodemon, assuming those have env var support?

**Comment by pdehaan** [comment]
@6a68 Is this still a thing if we move to Postgres, or does Postgres handle timezones more better?

**Comment by 6a68** [comment]
@pdehaan it's probably fine, since we don't do date math in the node server, and because any dates sent to DB or emitted by the API use the ISO format output by `Date.toJSON()`, for example, `"2015-01-15T00:22:47.493Z"`.
