### ISSUE TITLE
strip out trailing slashes

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#73]
hapi is fairly stupid about mapping `/v1/visits/` to `/v1/visits`. Build some middleware to handle this before routing.

**Comment by 6a68** [comment]
lol, just discovered the `stripTrailingSlashes` option deep in the hapi API docs :-)

should be an easy fix

**Comment by pdehaan** [comment]
![](http://i0.kym-cdn.com/photos/images/newsfeed/000/017/668/Mao_RTFM_vectorize_by_cmenghi.png?1318992465)

**Comment by pdehaan** [comment]
OK, this seems like an easy tweak, but I'm a bit confused...

> `stripTrailingSlash` - removes trailing slashes on incoming paths. Defaults to `false`.
&mdash; via http://hapijs.com/api#new-serveroptions

Using the default value of `false`, if I go to http://0.0.0.0:3001/v1/visits/ locally it says "hello world", but if I go to http://0.0.0.0:3001/v1/visits then it 404s, if my route is:

```js
{
    method: 'GET',
    path: '/v1/visits/',
    handler: function (request, reply) {
      reply('hello world!');
    }
  }
```

Are you saying you want `/v1/visits/` and `/v1/visits` to try and go to the same place and you want me to set `stripTrailingSlash` to `true` in the server config?

**Comment by pdehaan** [comment]
Here's the syntax, for when we want to change it in the future (so I don't have to look up the docs again):

```js
var server = new Hapi.Server();
server.connection({
  host: '0.0.0.0',
  port: 3001,
  router: {
    stripTrailingSlash: true
  }
});
```

Probably just get away with hardcoding the value as it probably doesn't make sense to put it in the Convict config.

**Comment by 6a68** [comment]
@pdehaan o hai, sorry, my notifications for this repo aren't quite right yet :-\

I think we should specify all the routes *without* the trailing slash, then set `stripTrailingSlash: true`. Just from a RESTful standpoint, that seems like the better approach: we don't want the `/visits/` resource, which looks funny, like a directory or something; we want the `/visits` resource.

PRs welcome! Thanks for digging into this one
