### ISSUE TITLE
deploy one-off dev stack on AWS + write docs

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#8]
* build out the basic stack on AWS
* take tons of screenshots (I find the AWS dashboard super confusing to navigate)
* put the docs someplace (README? docs folder?)

**Comment by 6a68** [comment]
@nchapman is it just me or is this basically done?

**Comment by 6a68** [comment]
@dannycoates That would be awesome! We still have some kinda big chunks to get sorted, maybe in a couple of weeks, though ^_^

**Comment by nchapman** [comment]
Our very basic stack is online. Just need to finish up the documentation.
