### ISSUE TITLE
DB migrations

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#92]
We will need these when we go to production. Figure them out.

**Comment by 6a68** [comment]
knex/bookshelf seem interesting, maybe

**Comment by 6a68** [comment]
ughhhh

- node-db-migrate has a six month old pull request to add postgres foreign key support (https://github.com/kunklejr/node-db-migrate/pull/181)
- sequelize just added migration support in the most recent release, so it's just barely baked. it depends on gulp, fml.
- knex doesn't handle really basic stuff in their migrations either https://github.com/tgriesser/knex/issues/46#issuecomment-72344915

**Comment by 6a68** [comment]
looks like @chilts's pg-patcher is our solution; everything else is bloated and yet incomplete enough that we'll need to write out all the raw SQL anyway. w00t

**Comment by 6a68** [comment]
Basic approach for elasticsearch: http://www.elasticsearch.org/blog/changing-mapping-with-zero-downtime/

**Comment by chilts** [comment]
Cool. Feel free to report bugs or offer suggestions of improvement. For example, in the mysql-patcher, @rfk has just added the ability to create a patch object which has various public methods on it so you're in control of the patching process a bit more than just `.patch()`. Am not saying that's coming to pg-patcher but if it's useful, I could add it. :)

**Comment by 6a68** [comment]
@chilts awesome! I'm just happy to not have to write the code that sorts and loops through the migrations in order ;-) My only concern is that `async` doesn't have a great story around error handling - but since you're using postgres transactions to enforce all-or-nothing semantics, it's great for our needs as written :-)
